"""Add Relationship betwween frebie and developer

Revision ID: bc4d62f681ef
Revises: c001d5a4d251
Create Date: 2024-03-26 12:51:09.206234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4d62f681ef'
down_revision = 'c001d5a4d251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
